/**
 * Famous dishes with Wikipedia article titles for HD photos + factual context.
 * IMDB = movies (not food). TheMealDB = free food API (used for real ingredients).
 */
export const FAMOUS_DISHES = [
  // ── Indian veg classics ──
  { name: "Masala Dosa", wikiTitle: "Masala dosa", cuisine: "south-indian", mealType: "breakfast", diet: ["veg"] },
  { name: "Idli", wikiTitle: "Idli", cuisine: "south-indian", mealType: "breakfast", diet: ["veg"] },
  { name: "Sambar", wikiTitle: "Sambar (dish)", cuisine: "south-indian", mealType: "lunch", diet: ["veg"] },
  { name: "Paneer Butter Masala", wikiTitle: "Paneer butter masala", cuisine: "north-indian", mealType: "dinner", diet: ["veg"] },
  { name: "Palak Paneer", wikiTitle: "Palak paneer", cuisine: "north-indian", mealType: "lunch", diet: ["veg"] },
  { name: "Dal Makhani", wikiTitle: "Dal makhani", cuisine: "punjabi", mealType: "lunch", diet: ["veg"] },
  { name: "Dal Tadka", wikiTitle: "Dal tadka", cuisine: "north-indian", mealType: "lunch", diet: ["veg"] },
  { name: "Chole Bhature", wikiTitle: "Chole bhature", cuisine: "punjabi", mealType: "breakfast", diet: ["veg"] },
  { name: "Rajma", wikiTitle: "Rajma", cuisine: "punjabi", mealType: "lunch", diet: ["veg"] },
  { name: "Aloo Gobi", wikiTitle: "Aloo gobi", cuisine: "north-indian", mealType: "lunch", diet: ["veg"] },
  { name: "Baingan Bharta", wikiTitle: "Baingan bharta", cuisine: "north-indian", mealType: "lunch", diet: ["veg"] },
  { name: "Samosa", wikiTitle: "Samosa", cuisine: "indian", mealType: "snack", diet: ["veg"] },
  { name: "Pav Bhaji", wikiTitle: "Pav bhaji", cuisine: "maharashtrian", mealType: "snack", diet: ["veg"] },
  { name: "Dhokla", wikiTitle: "Dhokla", cuisine: "gujarati", mealType: "breakfast", diet: ["veg"] },
  { name: "Poha", wikiTitle: "Poha (dish)", cuisine: "indian", mealType: "breakfast", diet: ["veg"] },
  { name: "Upma", wikiTitle: "Upma", cuisine: "south-indian", mealType: "breakfast", diet: ["veg"] },
  { name: "Biryani", wikiTitle: "Biryani", cuisine: "hyderabadi", mealType: "lunch", diet: ["non-veg"] },
  { name: "Hyderabadi Biryani", wikiTitle: "Hyderabadi biryani", cuisine: "hyderabadi", mealType: "lunch", diet: ["non-veg"] },
  { name: "Butter Chicken", wikiTitle: "Butter chicken", cuisine: "punjabi", mealType: "dinner", diet: ["non-veg"] },
  { name: "Chicken Tikka", wikiTitle: "Chicken tikka", cuisine: "punjabi", mealType: "snack", diet: ["non-veg"] },
  { name: "Tandoori Chicken", wikiTitle: "Tandoori chicken", cuisine: "punjabi", mealType: "dinner", diet: ["non-veg"] },
  { name: "Fish Curry", wikiTitle: "Fish curry", cuisine: "bengali", mealType: "lunch", diet: ["non-veg"] },
  { name: "Rasgulla", wikiTitle: "Rasgulla", cuisine: "bengali", mealType: "snack", diet: ["veg"] },
  { name: "Gulab Jamun", wikiTitle: "Gulab jamun", cuisine: "indian", mealType: "snack", diet: ["veg"] },
  { name: "Jalebi", wikiTitle: "Jalebi", cuisine: "indian", mealType: "snack", diet: ["veg"] },
  { name: "Lassi", wikiTitle: "Lassi", cuisine: "punjabi", mealType: "snack", diet: ["veg"] },
  { name: "Naan", wikiTitle: "Naan (bread)", cuisine: "north-indian", mealType: "dinner", diet: ["veg"] },
  { name: "Roti", wikiTitle: "Roti", cuisine: "indian", mealType: "lunch", diet: ["veg"] },
  { name: "Paratha", wikiTitle: "Paratha", cuisine: "punjabi", mealType: "breakfast", diet: ["veg"] },
  { name: "Khichdi", wikiTitle: "Khichdi", cuisine: "indian", mealType: "lunch", diet: ["veg"] },
  // ── World famous ──
  { name: "Pizza", wikiTitle: "Pizza", cuisine: "italian", mealType: "dinner", diet: ["veg"] },
  { name: "Pasta", wikiTitle: "Pasta", cuisine: "italian", mealType: "dinner", diet: ["veg"] },
  { name: "Sushi", wikiTitle: "Sushi", cuisine: "japanese", mealType: "dinner", diet: ["non-veg"] },
  { name: "Ramen", wikiTitle: "Ramen", cuisine: "japanese", mealType: "lunch", diet: ["non-veg"] },
  { name: "Tacos", wikiTitle: "Taco", cuisine: "mexican", mealType: "dinner", diet: ["non-veg"] },
  { name: "Burrito", wikiTitle: "Burrito", cuisine: "mexican", mealType: "lunch", diet: ["non-veg"] },
  { name: "Pad Thai", wikiTitle: "Pad thai", cuisine: "thai", mealType: "dinner", diet: ["non-veg"] },
  { name: "Tom Yum", wikiTitle: "Tom yum", cuisine: "thai", mealType: "lunch", diet: ["non-veg"] },
  { name: "Hummus", wikiTitle: "Hummus", cuisine: "continental", mealType: "snack", diet: ["veg"] },
  { name: "Falafel", wikiTitle: "Falafel", cuisine: "continental", mealType: "snack", diet: ["veg"] },
  { name: "Croissant", wikiTitle: "Croissant", cuisine: "continental", mealType: "breakfast", diet: ["veg"] },
  { name: "Caesar Salad", wikiTitle: "Caesar salad", cuisine: "continental", mealType: "lunch", diet: ["non-veg"] },
  { name: "French Fries", wikiTitle: "French fries", cuisine: "continental", mealType: "snack", diet: ["veg"] },
  { name: "Hamburger", wikiTitle: "Hamburger", cuisine: "continental", mealType: "dinner", diet: ["non-veg"] },
  { name: "Dim Sum", wikiTitle: "Dim sum", cuisine: "chinese", mealType: "snack", diet: ["non-veg"] },
  { name: "Fried Rice", wikiTitle: "Fried rice", cuisine: "chinese", mealType: "lunch", diet: ["veg"] },
  { name: "Spring Rolls", wikiTitle: "Spring roll", cuisine: "chinese", mealType: "snack", diet: ["veg"] },
  { name: "Miso Soup", wikiTitle: "Miso soup", cuisine: "japanese", mealType: "lunch", diet: ["veg"] },
  { name: "Paella", wikiTitle: "Paella", cuisine: "continental", mealType: "dinner", diet: ["non-veg"] },
  { name: "Ratatouille", wikiTitle: "Ratatouille", cuisine: "continental", mealType: "dinner", diet: ["veg"] },
];
